name: hn_app
description: A new Flutter application.

version: 0.0.2+2

dependencies:
  url_launcher: any

  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^6.1.3

  http: ^0.11.3

  rxdart: ^0.18.1

  font_awesome_flutter: ^8.0.0

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator:
    git: 
      url: https://github.com/efortuna/built_value.dart.git/
      path: built_value_generator

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
    - family: Garamond
      fonts:
      - asset: fonts/EBGaramond-Regular.ttf
      - asset: fonts/EBGaramond-Italic.ttf
        style: italic
      - asset: fonts/EBGaramond-Bold.ttf
        weight: 700
      - asset: fonts/EBGaramond-BoldItalic.ttf
        weight: 700
        style: italic
