name: hn_app
description: A new Flutter application.

version: 0.0.2+2

environment:
  sdk: ">=2.3.0-dev.0.5.flutter-a1668566e5 <3.0.0"

dependencies:
  moor_flutter: ^1.4.0
  url_launcher: ^5.0.2

  built_collection: ^4.2.2
  built_value: ^6.5.0

  http: ^0.12.0+2

  font_awesome_flutter: ^8.4.0

  webview_flutter: ^0.3.7+1

  provider: ^2.0.1

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  shared_preferences: ^0.5.2+1

dev_dependencies:
  build_runner: ^1.4.0
  built_value_generator: ^6.5.0
  moor_generator: ^1.4.0

  test: ^1.6.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Garamond
      fonts:
      - asset: fonts/EBGaramond-Regular.ttf
      - asset: fonts/EBGaramond-Italic.ttf
        style: italic
      - asset: fonts/EBGaramond-Bold.ttf
        weight: 700
      - asset: fonts/EBGaramond-BoldItalic.ttf
        weight: 700
        style: italic
